### PR TITLE
Re-add Firefly support by updating the api for the new Firefly-vis pypi project

### PR DESCRIPTION
**Pull request by agurvich**
## PR Summary

firefly_api has been deprecated, so much so I tried to remove all traces of its existence from the internet.
That broke the yt CI. My bad. Now that I have uploaded the Firefly source files and the new api to PyPi
I needed to update how yt integrates with Firefly. 

https://github.com/yt-project/yt/pull/3419

## PR Checklist

- [x] New features are documented, with docstrings and narrative docs
- [x] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Hi @agurvich, I think you mistakenly opened this PR on the wrong repo, this is my personal fork, not the main one :)

**Comment by agurvich** [comment]
I was under the impression that if you merged this PR into your personal fork then you could merge https://github.com/yt-project/yt/pull/3419 into the main repo. Should I open a new PR straight into the main repo instead?

**Comment by neutrinoceros** [comment]
Yes please, do that. I don't want the main branch of this fork to diverge from that of the main repo

**Comment by agurvich** [comment]
check out: https://github.com/yt-project/yt/pull/3435

**Pull request closed without merging**
